### ISSUE TITLE
Trouble understanding

### ISSUE THREAD

**Issue by Thar-un** [chintan1995/Image-Denoising-using-Deep-Learning#3]
Hi, I'm having trouble understanding the Avg_pool_Unet_Upsample_msfe and  Multi_scale_feature_extraction architecture you have implemented. If possible do you have any documentation that explains, how the input is denoised line by line? or any resource that you can point me to it.

Thanks in advance

**Comment by chintan1995** [comment]
You can refer the research paper, where the authors have explained how and why this pyramid layer (msfe) works.
https://arxiv.org/pdf/1908.00273.pdf
